// marka_adi (büyük harf) → /logos/{slug}.svg dosya adı
const LOGO_MAP: Record<string, string> = {
  // Popüler binek
  "TOYOTA": "toyota",
  "VOLKSWAGEN": "volkswagen",
  "BMW": "bmw",
  "MERCEDES": "mercedes",
  "FORD": "ford",
  "FORD /USA": "ford",
  "RENAULT": "renault",
  "RENAULT (OYAK)": "renault",
  "HYUNDAI": "hyundai",
  "KIA": "kia",
  "PEUGEOT": "peugeot",
  "FIAT": "fiat",
  "TOFAS-FIAT": "fiat",
  "OPEL": "opel",
  "AUDI": "audi",
  "SKODA": "skoda",
  "VOLVO": "volvo",
  "VOLVO-TR": "volvo",
  "HONDA": "honda",
  "NISSAN": "nissan",
  "SUZUKI": "suzuki",
  "SEAT": "seat",
  "CITROEN": "citroen",
  "DACIA": "dacia",
  "JEEP": "jeep",
  "MITSUBISHI": "mitsubishi",
  "MAZDA": "mazda",
  "LAND ROVER": "landrover",
  "RANGE ROVER": "landrover",
  "MINI": "mini",
  "PORSCHE": "porsche",
  "TESLA": "tesla",
  "MG": "mg",
  "JAGUAR": "jaguar",
  "SMART": "smart",
  "INFINITI": "infiniti",
  "CUPRA": "cupra",
  "DS": "ds",
  "LEXUS": "lexus",
  "DAIHATSU": "daihatsu",
  "ISUZU": "isuzu",
  "TOGG": "togg",
  // Lüks & spor
  "ALFA ROMEO": "alfaromeo",
  "FERRARI": "ferrari",
  "MASERATI": "maserati",
  "LAMBORGHINI": "lamborghini",
  "BENTLEY": "bentley",
  "ASTON MARTIN": "astonmartin",
  "ROLLS-ROYCE": "rollsroyce",
  "MCLAREN": "mclaren",
  "BUGATTI": "bugatti",
  "KOENIGSEGG": "koenigsegg",
  "LOTUS": "lotus",
  "MAYBACH": "maybach",
  "LANCIA": "lancia",
  // Amerikan
  "CADILLAC": "cadillac",
  "CHEVROLET": "chevrolet",
  "CHRYSLER": "chrysler",
  "DODGE/USA": "dodge",
  "GMC": "gmc",
  "LINCOLN": "lincoln",
  "BUICK": "buick",
  // EV & yeni nesil
  "POLESTAR": "polestar",
  "LUCID": "lucid",
  "BYD": "byd",
  "XPENG": "xpeng",
  "CHERY": "chery",
  // Diğer global
  "SUBARU": "subaru",
  "SAAB": "saab",
  "SSANGYONG": "ssangyong",
  "KGMOBILITY": "kgmobility",
  "LADA": "lada",
  "MAHINDRA": "mahindra",
  "PROTON": "proton",
  "GEELY": "geely",
  "LYNK-CO": "lynkco",
  // Ticari & diğer
  "MAN": "man",
  "SCANIA": "scania",
  "TATA": "tata",
  "KTM": "ktm",
};

export function getLogoSlug(markaAdi: string): string | null {
  return LOGO_MAP[markaAdi.toUpperCase()] ?? null;
}
