// marka_adi (büyük harf) → /logos/{slug}.svg dosya adı
const LOGO_MAP: Record<string, string> = {
  "TOYOTA": "toyota",
  "VOLKSWAGEN": "volkswagen",
  "BMW": "bmw",
  "MERCEDES": "mercedes",
  "FORD": "ford",
  "FORD /USA": "ford",
  "RENAULT": "renault",
  "RENAULT (OYAK)": "renault",
  "HYUNDAI": "hyundai",
  "KIA": "kia",
  "PEUGEOT": "peugeot",
  "FIAT": "fiat",
  "TOFAS-FIAT": "fiat",
  "OPEL": "opel",
  "AUDI": "audi",
  "SKODA": "skoda",
  "VOLVO": "volvo",
  "VOLVO-TR": "volvo",
  "HONDA": "honda",
  "NISSAN": "nissan",
  "SUZUKI": "suzuki",
  "SEAT": "seat",
  "CITROEN": "citroen",
  "DACIA": "dacia",
  "JEEP": "jeep",
  "MITSUBISHI": "mitsubishi",
  "MAZDA": "mazda",
  "LAND ROVER": "landrover",
  "RANGE ROVER": "landrover",
  "MINI": "mini",
  "PORSCHE": "porsche",
  "TESLA": "tesla",
  "MG": "mg",
  "JAGUAR": "jaguar",
  "SMART": "smart",
  "INFINITI": "infiniti",
  "ALFA ROMEO": "alfaromeo",
  "FERRARI": "ferrari",
  "MASERATI": "maserati",
  "LAMBORGHINI": "lamborghini",
  "BENTLEY": "bentley",
  "ASTON MARTIN": "astonmartin",
  "ROLLS-ROYCE": "rollsroyce",
  "SUBARU": "subaru",
  "BUGATTI": "bugatti",
  "CADILLAC": "cadillac",
  "CHEVROLET": "chevrolet",
  "CHRYSLER": "chrysler",
  "LADA": "lada",
  "LUCID": "lucid",
  "MAHINDRA": "mahindra",
  "MCLAREN": "mclaren",
  "POLESTAR": "polestar",
  "PROTON": "proton",
};

export function getLogoSlug(markaAdi: string): string | null {
  return LOGO_MAP[markaAdi.toUpperCase()] ?? null;
}
